In [2]:
# 1. Import the numpy package under the name np 

import numpy as np

In [6]:
# 3. Create a null vector of size 10 
# null vector는 zero vector를 뜻함

a = np.zeros(10)


In [14]:
# 4.How to find the memory size of any array 
# array의 메모리 사이즈 찾는 방법

np.shape(a)
a.nbytes

80

In [12]:
# 5. size가 10인 null vector를 만들고 5번째 원소는 1로 만들기

b = np.zeros(10)
b[4] =1
b


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
# 7. Create a vector with values ranging from 10 to 49 

c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
# 8. Reverse a vector (first element becomes last)
# 위 배열의 원소를 뒤집는 문제

c[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [18]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 
# 0부터 8을 원소로 가지는 3 x 3의 행렬을 만들어라

d = np.arange(0,9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] 
# [1,2,0,0,4,0]에서 0이 아닌 요소의 인덱스 찾기

e = np.array([1,2,0,0,4,0])
             
np.where(e != 0)



(array([0, 1, 4], dtype=int64),)

In [33]:
# 11. Create a 3x3 identity matrix 
# 3 x 3의 항등행렬을 만들어라

a = np.zeros((3,3))
a = a.astype('int32')

a[[0,1,2],[0,1,2]] = 1

a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
# 12. Create a 3x3x3 array with random values 
# 무작위 원소를 가진 3x3x3의 array를 만들어라

b = np.random.rand(3,3,3)
b


array([[[0.07157491, 0.73642033, 0.20459725],
        [0.64692363, 0.7779454 , 0.32402558],
        [0.45701389, 0.41577612, 0.54723969]],

       [[0.62234887, 0.78403494, 0.40942856],
        [0.13629793, 0.31296501, 0.80975027],
        [0.8889366 , 0.01286495, 0.65401768]],

       [[0.56357873, 0.82529364, 0.70309781],
        [0.62405343, 0.79732554, 0.87772925],
        [0.84275562, 0.47971314, 0.8063374 ]]])

In [52]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
# 10x10의 무작위 원소를 가진 array를 만들고 최솟값과 최댓값을 찾아라.

a = np.random.rand(10,10)

np.max(a), np.min(a)


(0.9940583896578787, 0.025045709954665707)

In [55]:
# 14. Create a random vector of size 30 and find the mean value 
# size가 30인 무작위 벡터를 만들고 평균값을 구하라

a = np.random.rand(30)
np.mean(a)


0.5457614157877695

In [59]:
# 15. Create a 2d array with 1 on the border and 0 inside 
# 테두리의 원소가 1이고 안쪽 원소가 0인 2차원 배열을 만들어라

a = np.ones((3,3))
a = a.astype('int32')
a[1,1] = 0
a

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [161]:
# 16. How to add a border (filled with 0's) around an existing array?
# 기존 배열에 (0으로 채워진)새로운 테두리를 추가하는 방법은?

a = np.ones((4,4))

a[:][[0,-1]] = 0
a[:,[0, -1]] = 0

a


array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 17. What is the result of the following expression?

#1 0 * np.nan
# nan

#2 np.nan == np.nan
# False  // nan을 비교연산하면 무조건 False

#3 np.inf > np.nan
#False   # np.inf ??

#4 np.nan - np.nan
# nan

#5 np.nan in set([np.nan])
# True # np.nan은 np.nan의 집합 내에 속한다.

#6 0.3 == 3 * 0.1
# Fasle
# 3.0 * 0.1은 0.3으로 나오지 않고 0.300000000004로 출력된다. 이는 부동소수점에 의한 오차를 나타낸다.

In [78]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#대각선 바로 아래에 값 1,2,3,4가 있는 5x5 행렬 만들기

a = np.zeros((5,5))
a[[1,2,3,4], [0,1,2,3]] = [1,2,3,4] # 슬라이싱으로 하면 안 됨.
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [79]:
a[1:5, :4]

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

In [105]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
# 8x8 매트릭스를 만들고 체커보드 패턴으로 채웁니다.

a = np.zeros((8,8))
a = a.astype('int32')

a[::2 ,[0,2,4,6]] = 1
a[1::2 ,[1,3,5,7]] = 1
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [104]:
a = np.zeros((8,8))
a = a.astype('int32')
a[::2 ,1::2] = 1
a[1::2 ,::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [109]:
# 22. Normalize a 5x5 random matrix (★☆☆)
# 5x5 랜덤 행렬 정규화

a = np.random.normal(size = (5,5))
a


array([[-1.04597816,  0.70809797, -1.69399342, -1.0326263 ,  0.86891948],
       [ 0.3921338 ,  0.38371107, -0.31868342,  0.17059027, -0.11678673],
       [ 0.43330155, -0.34435758, -1.32663293,  2.70666399, -0.33502262],
       [-1.75876471, -1.01213369,  1.38900167,  1.94787752,  0.57116971],
       [ 1.1689823 , -0.58662587,  0.4046052 ,  0.29617969, -0.21766212]])

In [113]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
# 5x3 행렬에 3x2 행렬(실제 행렬 곱)을 곱합니다.

a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)

a @ b



array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [119]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
# 1차원 배열에서 3에서 8사이 값을 음수화하여라

a = np.arange(10)
-a[3:9]

array([-3, -4, -5, -6, -7, -8])

26. What is the output of the following script? (★☆☆)
- 다음 스크립트의 출력은 어떻게 됩니까?

In [128]:
# 통계함수에서 피연산자는 iterator 다 들어감.
# range() 도 해당 원소 모두 더함.
print(sum(range(5)))


10


In [163]:
# ?????????
print(sum(range(5),-1))

10


In [162]:
from numpy import *
print(sum(range(5),-1))

10


In [ ]:
print(sum(range(5),-1))

In [129]:
from numpy import *
print(sum(range(5),-1))

9
10
10
10


In [135]:
# 27. Consider an integer vector Z, which of these expressions are legal? 
# 정수 벡터 Z를 생각해보십시오.이 표현식 중 어느 것이 합법적입니까

Z = np.arange(10)

print(Z**Z) # ok
print(2 << Z >> 2) # ok
print(Z <- Z) # ok
print(1j*Z) # ok
print(Z/1/1) # ok
# print(Z<Z>Z) # no

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 비트연산자
1. "<<"는 연산은 왼쪽으로 1비트 밀때마다 두 배씩 늘어납니다.
- n << m : n * 2의 m승

2. ">>" 연산은 오른쪽으로 1비트 밀때마다 1/2씩 줄어듭니다.
- n >> m : n / 2의 m승

In [132]:
print(2 << Z) # 2*2의 z승 
print(Z >> 2) # 2/2의 z승 

[   2    4    8   16   32   64  128  256  512 1024]
[0 0 0 0 1 1 1 1 2 2]


In [167]:
# 28. What are the result of the following expressions? (★☆☆)
# 다음 표현의 결과는 무엇입니까?

a = np.array(0)
b = np.array(0)

b


array(0)

In [146]:
print(np.array(0) / np.array(0)) # 0/0 

nan


C:\Users\CSYJ\anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [147]:
0//0

ZeroDivisionError: integer division or modulo by zero

In [ ]:
print(np.array(0) // np.array(0))

In [139]:
print(np.array([np.nan]).astype(int).astype(float))
 

0
[-2.14748365e+09]


C:\Users\CSYJ\anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [157]:
# 30. How to find common values between two arrays? (★☆☆)
# 두 배열 사이의 공통 값을 찾는 방법은 무엇입니까?

arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

[i for i in arr2 if arr1 == i]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()