# 배열을 파일에 저장 및 불러오기
- ## 바이너리 파일로 저장/불러오기
    - 메모리에 있는 그대로
    - ### np.save("파일경로", 배열)
        - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
        - 파일명에 확장자로 npy를 붙인다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로") 
        - 파일에 저장된 배열을 불러온다.
    - ### np.savez("파일경로", 이름=배열, 이름=배열, ...)
        - 여러개의 배열을 저장할 때 사용
        - 파일명에 확장자로 npz가 붙는다.
        - 내부적으로 압축해서 저장한다.
        - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기 (csv)
    - ### savetxt("파일경로", 배열 [, delimiter='공백') 
        - 텍스트 형태로 저장.
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
        - 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)
    - ### loadtxt("파일경로" [,dtype=float, delimiter=공백)

In [1]:
import numpy as np

a = np.array([1,5,8,9,10]) # 1차원
b = np.ones(shape = (3,4,2)) # 3차원
c = np.random.normal(size = (5,10)) # 2차원

print(a.shape, b.shape, c.shape)


(5,) (3, 4, 2) (5, 10)


In [5]:
# 저장 - binary 형식
# a 배열을 /a.npy 파일에 저장

import os

# 저장할 디렉토리가 없으면 만들어라
save_dir = 'save_data' 
if not os.path.isdir(save_dir): # 디렉토리가 있는지 여부 확인 - 디렉토리가 없으면
    os.mkdir(save_dir) # 디렉토리 생성 (있으면 오류나서 if문 처리해주기)

np.save('save_data/a', a) 

In [6]:
np.save('save_data/b', b)
np.save('save_data/c', c)

In [8]:
# binary로 저장된 배열을 불러오기
a2 = np.load('save_data/a.npy')
a2

array([ 1,  5,  8,  9, 10])

In [9]:
b2 = np.load('save_data/b.npy')
b2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [10]:
c2 = np.load('save_data/b.npy')
c2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [11]:
# 세 개의 배열을 한 파일에 저장 (N개를 한 파일에 저장)
np.savez('save_data/all', arr_a=a, arr_b=b, arr_c=c)

In [ ]:
# npz 파일 읽어오기 - load()
arr_all = np.load('save_data/all.npz')

In [13]:
# 저장할 때 지정한 이름 조회
arr_all.files

['arr_a', 'arr_b', 'arr_c']

In [14]:
# 불러온 npz파일에서 각 배열 불러오기 
a3 = arr_all['arr_a']
b3 = arr_all['arr_b']
c3 = arr_all['arr_c']

In [15]:
a,a3

(array([ 1,  5,  8,  9, 10]), array([ 1,  5,  8,  9, 10]))

- 텍스트 파일로 저장 = > 1차원, 2차원 배열만 가능

In [19]:
# 1차원 
# delimiter 상관없음. 설정해줘도 원소 당 \n로
# 기본이 실수로 저장됨.
np.savetxt('save_data/a_txt.csv', a)

In [21]:
np.savetxt('save_data/c.csv', c, delimiter=',')

In [23]:
# 저장되어있는 구분자와 동일한 것을 지정한다. 
c4 = np.loadtxt('save_data/c.csv', delimiter = ',')
c4

array([[-0.09565259, -1.25854295, -0.15543603,  3.27987503, -2.34520922,
        -0.66403495, -0.29347092, -0.8722688 , -0.05872433,  0.28209193],
       [ 0.74703488, -0.90347318, -1.22281773,  0.23410479, -0.28557795,
         0.73440895, -0.86475544, -1.27432918, -0.34574281,  0.2270336 ],
       [ 0.44104281, -0.60535399, -2.13033811,  0.40378215, -1.25446813,
         2.72436253, -1.12600656, -0.89775721, -2.00646919, -2.15162935],
       [-0.31427384, -0.61700352,  0.55622468,  1.41322763, -0.55259957,
        -0.25543099,  0.26532183, -0.57033572, -0.74386418,  2.16820366],
       [ 1.00879706, -0.73171976,  2.23174747, -0.48258047, -0.75171223,
         1.69571106,  0.24702797, -0.20032806, -1.1706279 ,  0.19516239]])

In [24]:
# 3차원 배열은 저장 안됨.
np.savetxt('test', b)

ValueError: Expected 1D or 2D array, got 3D array instead

In [27]:
# txt 저장할 때 float64 로 저장됨. -> 불러올 때 타입 정해서

a5 = np.loadtxt('save_data/a_txt.csv', dtype = 'int32')
a5.dtype

dtype('int32')

In [31]:
import pandas as pd

df = pd.read_csv('save_data/c.csv', header=None )
df

# 정수로 불러올려면?

0         1         2         3         4         5         6  \
0 -0.095653 -1.258543 -0.155436  3.279875 -2.345209 -0.664035 -0.293471   
1  0.747035 -0.903473 -1.222818  0.234105 -0.285578  0.734409 -0.864755   
2  0.441043 -0.605354 -2.130338  0.403782 -1.254468  2.724363 -1.126007   
3 -0.314274 -0.617004  0.556225  1.413228 -0.552600 -0.255431  0.265322   
4  1.008797 -0.731720  2.231747 -0.482580 -0.751712  1.695711  0.247028   

          7         8         9  
0 -0.872269 -0.058724  0.282092  
1 -1.274329 -0.345743  0.227034  
2 -0.897757 -2.006469 -2.151629  
3 -0.570336 -0.743864  2.168204  
4 -0.200328 -1.170628  0.195162